restaurant_name: 'Blue Sahara'
r_address_line1: 'Near Bank of Baroda, Ambethan Chowk'
r_address_line2: 'Pune Nasik Road, Chakan'
r_address_line3: 'Maharashtra - 410501'
r_website: 'http://www.facebook.com/BlueSahara'
r_phone: '02135 249036, 9850572491'
ticket_footer: 'Thank you. Visit Again'
